# internal/prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'go-backend'
    scheme: https
    static_configs:
      - targets: ['host.docker.internal:8080']
    tls_config:
      ca_file: /etc/prometheus/certs/server.crt
      insecure_skip_verify: false
